footprint: [[-0.15, -0.15], [-0.15, 0.15], [0.22, 0.15], [0.22, -0.15]]
#footprint: [[-0.175, -0.175], [-0.175, 0.175], [0.175, 0.175], [0.175, -0.175]]
footprint_padding: 0.01
map_type: costmap

obstacle_range: 3
raytrace_range: 3.5

transform_tolerance: 0.3

min_obstacle_height: 0.0
max_obstacle_height: 0.4

#layer definitions
static:
    enable: true
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    enabled: true
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation:
    enabled: true
    inflation_radius: 0.25
    cost_scaling_factor: 0.5

