global_frame: odom
robot_base_frame: robot_footprint
update_frequency: 10
publish_frequency: 2.0
width: 3
height: 3
resolution: 0.04
static_map: false
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

