use_map_topic: true
odom_model_type: diff-corrected
odom_frame_id: odom
global_frame_id: map
base_frame_id: robot_footprint
tf_broadcast: true

min_particles: 100
max_particles: 300
kld_err: 0.04 #0.1
kdl_z: 0.99 #0.99
update_min_d: 0.0
update_min_a: 0.0
resample_interval: 1
transform_tolerance: 0.6

laser_max_beams: 60
laser_max_range: 6.0
laser_z_hit: 0.9 #0.95 #ria 0.5
laser_z_short: 0.05 #0.1 #ria 0.05
laser_z_max: 0.05 #0.05
laser_z_rand: 0.5 #0.1 #ria 0.5
laser_likelihood_max_dist: 2.0
laser_sigma_hit: 0.2 #0.25 #ria 0.2
laser_lambda_short: 0.1
laser_model_type: likelihood_field


odom_alpha1: 0.2  # expect noise of rotation estimate from rotation movement
odom_alpha2: 0.12 # expect noise of rotation estimate from translation movement
odom_alpha3: 0.12 # expect noise of translation estimate from translation movement
odom_alpha4: 0.12 # expect noise of translation estimate from rotation movement
#odom_alpha5: 0.1
initial_pose_x: 0
initial_pose_y: 0
initial_pose_a: 0

recovery_alpha_slow: 0.01
recovery_alpha_fast: 0.01
